# Generated by Django 2.1 on 2018-08-18 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180815_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique library ID for this book', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='media',
            field=models.CharField(default='paperback', help_text='Type of media (e.g. hardback, audiobook)', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the language the book is written in (e.g. Chinese, Farsi).', max_length=25),
        ),
    ]
