# Generated by Django 2.1 on 2018-08-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180828_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_author', 'Can add, edit or delete author'),)},
        ),
    ]
