# Generated by Django 2.1 on 2018-08-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180828_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Can add, edit, delete books'),)},
        ),
    ]
